set rnu
set nuw=2
syntax on
filetype plugin indent on
set autoindent
set backspace=indent,eol,start
set ruler
set listchars=eol:\\,tab:>-,trail:~,extends:>,precedes:<
set list
set noexpandtab
set wildmode=list:longest
set incsearch
colorscheme ron
set showcmd

